spring:
  data:
    mongodb:
      uri: mongodb+srv://Admin:GSPTraders@gsp-traders.waaa7.mongodb.net/restaurant_db?retryWrites=true&w=majority&appName=GSP-Traders
server:
  port: 8081  # Avoid port conflicts with other services
